### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by ericborgos** [jon-tow/text-sed#1]
I would like to try text-sed, but my programmer and I were not able to install it.  It would be good if you had a requirements.txt file for it. For example:
Will it only work with CUDA 11.6 ?
Is Slurm required?
Is openmpi required?
I don't normally use any of those. I have done a lot of work with LLMs and image diffusion models and I understand all the concepts in your paper, I just would like to get the program working.

**Comment by jon-tow** [comment]
Hey @ericborgos ! You may need to update your `pip` version: `pip install --upgrade pip`. I'll add a `requirements.txt` later in the day, though let me know if the pip update resolves the issue for you.

Re your other questions:
- I've only tested on 11.6 and 11.7 so I'm not sure how well-supported it is beyond that. I can't think of any reasons it wouldn't work for a bit earlier CUDA version, say, 11.3.
- Slurm and OpenMPI are _not_ required.

**Comment by ericborgos** [comment]
I made some progress, but my programmer and I both get the same errors when trying to run train.sh . I am using Google Colab (CUDA 11.2) and he is using his local GPU (CUDA 11.3). The errors are: 
/content/text-sed/train.sh: line 16: module: command not found
/content/text-sed/train.sh: line 17: module: command not found
/content/text-sed/train.sh: line 18: /opt/intel/mpi/latest/env/vars.sh: No such file or directory
/content/text-sed/train.sh: line 47: scontrol: command not found
/content/text-sed/train.sh: line 48: scontrol: command not found
ERROR: ld.so: object '/opt/nccl/build/lib/libnccl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/content/text-sed/train.sh: line 50: scontrol: command not found
ERROR: ld.so: object '/opt/nccl/build/lib/libnccl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Node Count: 0
Host Names: 
/content/text-sed/train.sh: line 62: .env/bin/activate: No such file or directory

Installing it in Google Colab works fine using these commands:
!pip install --upgrade pip
!git clone https://github.com/jon-tow/text-sed
!cd /content/text-sed
!pip install -e /content/text-sed/".[dev, train]"

The errors are when I then run:
!bash /content/text-sed/train.sh

My programmer was able to get Minimal Text Diffusion (https://github.com/madaan/minimal-text-diffusion) working on Colab  but I would much rather experiment with your program as it is more advanced. I am trying to adapt text diffusion to search a database (using vectors).

**Comment by jon-tow** [comment]
`train.sh` is a Slurm script. To run training with [elastic launcher ](https://pytorch.org/docs/stable/elastic/run.html) use the `train.py` script.

**Comment by jon-tow** [comment]
@ericborgos the package should now be installable through `pip` on colab:
https://colab.research.google.com/drive/14KYyvYWtmVKITMltiIMn9zUjQ1ya6t9_?usp=sharing

Closing now but feel free to re-open if you have any other issues. Thanks for reporting!

**Comment by ericborgos** [comment]
Your Colab notebook installs fine, but is not usable.
When I run it like this:  !torchrun --nproc_per_node=1 train.py
it downoads the weights and data but then gives an error:
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: Tracking run with wandb version 0.13.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
Downloading: 100% 29.0/29.0 [00:00<00:00, 23.0kB/s]
Downloading: 100% 762/762 [00:00<00:00, 582kB/s]
Downloading: 100% 213k/213k [00:00<00:00, 241kB/s]
Downloading: 100% 436k/436k [00:01<00:00, 390kB/s]
Downloading: 100% 1.34G/1.34G [00:21<00:00, 60.9MB/s]
Some weights of the model checkpoint at bert-large-cased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Downloading and preparing dataset roc_stories/default to /root/.cache/huggingface/datasets/roc_stories/default/0.0.0/363ad38daea2588d19e4a72feb9440eff44f119a6df4e4e94beeb8f72f745d01...
Downloading data files:   0% 0/2 [00:00<?, ?it/s]
Downloading data:   0% 0.00/13.1M [00:00<?, ?B/s]
Downloading data:   0% 52.2k/13.1M [00:00<00:34, 374kB/s]
Downloading data:   2% 311k/13.1M [00:00<00:10, 1.24MB/s]
Downloading data:  10% 1.36M/13.1M [00:00<00:02, 4.07MB/s]
Downloading data:  36% 4.69M/13.1M [00:00<00:00, 13.3MB/s]
Downloading data:  54% 7.06M/13.1M [00:00<00:00, 16.0MB/s]
Downloading data: 100% 13.1M/13.1M [00:00<00:00, 16.4MB/s]
Downloading data files:  50% 1/2 [00:01<00:01,  1.55s/it]
Downloading data:   0% 0.00/14.5M [00:00<?, ?B/s]
Downloading data:   0% 54.3k/14.5M [00:00<00:38, 374kB/s]
Downloading data:   2% 322k/14.5M [00:00<00:11, 1.23MB/s]
Downloading data:   9% 1.36M/14.5M [00:00<00:03, 3.91MB/s]
Downloading data:  35% 5.14M/14.5M [00:00<00:00, 12.6MB/s]
Downloading data:  63% 9.21M/14.5M [00:00<00:00, 18.0MB/s]
Downloading data: 100% 14.5M/14.5M [00:00<00:00, 16.4MB/s]
Downloading data files: 100% 2/2 [00:03<00:00,  1.59s/it]
Extracting data files: 100% 2/2 [00:00<00:00, 1209.95it/s]
Dataset roc_stories downloaded and prepared to /root/.cache/huggingface/datasets/roc_stories/default/0.0.0/363ad38daea2588d19e4a72feb9440eff44f119a6df4e4e94beeb8f72f745d01. Subsequent calls will reuse this data.
100% 89/89 [00:10<00:00,  8.15ba/s]
  0% 0/200000 [00:00<?, ?it/s]You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
  0% 0/200000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    train(
  File "train.py", line 84, in train
    with torch.amp.autocast(
  File "/usr/local/lib/python3.8/dist-packages/torch/amp/autocast_mode.py", line 225, in __init__
    raise RuntimeError('Current CUDA Device does not support bfloat16. Please switch dtype to float16.')
RuntimeError: Current CUDA Device does not support bfloat16. Please switch dtype to float16.
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /content/text-sed/wandb/offline-run-20221229_123141-ifyezkl7
wandb: Find logs at: ./wandb/offline-run-20221229_123141-ifyezkl7/logs
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 505) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-29_12:33:00
  host      : 7212dfdccc1b
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 505)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by ericborgos** [comment]
If I instead run it like:
!python train.py
I get this error:
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    slurm.init_distributed_mode(args)
  File "/content/text-sed/text_sed/slurm.py", line 83, in init_distributed_mode
    args.local_rank = int(os.environ["LOCAL_RANK"])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'
